name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Test
        run: |
          go test -timeout 60m -covermode=atomic -coverprofile=coverage.tx -v ./...
          go tool cover -func=coverage.tx -o=coverage.out